#pragma once

typedef enum {
	STATE_START,
	STATE_FIND_SIDE_HOME1,
	STATE_FIND_SIDE_SEESAW,
	STATE_FIND_SIDE_HOME2,
	STATE_STARTED_RIGHT1,
	STATE_STARTED_RIGHT2,
	STATE_STARTED_LEFT1,
	STATE_STARTED_LEFT2,
	STATE_STARTED_LEFT3,
	STATE_STARTED_LEFT4,
	STATE_STARTED_LEFT5,

	STATE_STOPPING		// transition state to wait for robot to stop
} MainState;
